pool:
    name: ads-build-1es-hosted-pool
    demands: 
    - ImageOverride -equals ADS-Linux_Image

steps:
  - task: DockerInstaller@0
    displayName: Docker Installer
    inputs:
      dockerVersion: 17.09.0-ce
      releaseType: stable

  - script: docker pull mcr.microsoft.com/mssql/server:2019-latest
    displayName: Pull MSSQL Docker Image

  - script: 'docker run -e "ACCEPT_EULA=Y" -e "SA_PASSWORD=$(serverPassword)" -e "MSSQL_PID=Express"
    -p 1433:1433 --name sql1 -h sql1
    -d mcr.microsoft.com/mssql/server:2019-latest'
    displayName: Start Server in Docker Container
  - task: DownloadSecureFile@1
    displayName: 'Download secure file'
    inputs:
      secureFile: 'testsettings-test.json'

  - task: UseDotNet@2
    displayName: 'Use .NET Core sdk '
    inputs:
      useGlobalJson: true

  - task: NuGetAuthenticate@0

  - task: DotNetCoreCLI@2
    displayName: 'dotnet build'
    inputs:
      projects: '**/Microsoft.SqlTools.ServiceLayer.IntegrationTests.csproj'
      arguments: '/p:CodeCoverageBuild=true'

  - task: CopyFiles@2
    displayName: 'Copy testsettings file to bin'
    inputs:
      SourceFolder: '$(Agent.TempDirectory)'
      Contents: '**\testsettings-test.json'
      TargetFolder: '$(Build.SourcesDirectory)\test\Microsoft.SqlTools.ServiceLayer.IntegrationTests\bin\Debug\net6.0'

  - task: DotNetCoreCLI@2
    displayName: 'Run integration tests'
    inputs:
      command: test
      projects: '**/Microsoft.SqlTools.ServiceLayer.IntegrationTests.csproj'
      arguments: '--no-build'
      testRunTitle: 'SqlToolsService Integration Tests'
    enabled: false

  - task: VSTest@2
    displayName: 'Run integration tests with code coverage'
    inputs:
      testAssemblyVer2: '**/bin/Debug/**/Microsoft.SqlTools.ServiceLayer.IntegrationTests.dll'
      vsTestVersion: toolsInstaller
      runSettingsFile: 'azure-pipelines/testrun.runsettings'
      codeCoverageEnabled: true
      testRunTitle: 'SqlToolsService Integration Tests'
      rerunFailedTests: true
      rerunFailedThreshold: 15
      rerunMaxAttempts: 1
    continueOnError: true
